version: '3.8'

services:

  reactapp:
    build:
      context: ..
      dockerfile: ODocker/frontend/Dockerfile
      args:
        - GIT_TOKEN=${GIT_TOKEN}
    ports:
      - "3000:80"
    restart: on-failure

  main:
    build:
      context: ..
      dockerfile: ODocker/main/Dockerfile
      args:
        - GIT_TOKEN=${GIT_TOKEN}
    ports:
      - "50500:50500"
    environment:
      - ACCOUNT_SERVICE_API_URL=http://accountservice:50503
    restart: on-failure

  accountservice:
    build:
      context: ..
      dockerfile: ODocker/accountservice/Dockerfile
      args:
        - GIT_TOKEN=${GIT_TOKEN}
    ports:
      - "50503:50503"
    environment:
      - MAIN_SERVICE_API_URL=http://main:50500
    restart: on-failure

  questionservice:
    build:
      context: ..
      dockerfile: ODocker/questionsservice/Dockerfile
      args:
        - GIT_TOKEN=${GIT_TOKEN}
    ports:
      - "50502:50502"
    restart: on-failure

  nginx:
    build:
      context: ..
      dockerfile: ODocker/znginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    command: "certonly --webroot --webroot-path=/var/www/certbot --email hural061995@gmail.com --agree-tos --no-eff-email --domains op.kayacode.tech --staging"

  jenkins:
    build:
      context: ..
      dockerfile:  ODocker/zjenkins/Dockerfile
    ports:
      - "4123:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
    restart: on-failure

volumes:
  jenkins_home:
  data: {}  # Bu volume, Nginx ve Certbot arasında veri paylaşımı için kullanılacak.
